# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-22 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('ssn', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='SSN')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('dod', models.DateField(blank=True, null=True, verbose_name='Date of Death')),
                ('sex', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Male'), (2, 'Female')], default=0, verbose_name='Gender')),
            ],
            options={
                'verbose_name_plural': 'Person',
                'ordering': ['-name'],
            },
        ),
    ]
