# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-22 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.IntegerField(choices=[(1, 'Father'), (2, 'Mother'), (3, 'Brother'), (4, 'Sister'), (5, 'Husband'), (6, 'Wife'), (7, 'Uncle'), (8, 'Aunt'), (9, 'Grand Father'), (10, 'Grand Mother'), (11, 'Son'), (12, 'Daughter'), (13, 'Boy Friend'), (14, 'Girl Friend')])),
                ('of_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='of_person', to='Person.Person', verbose_name='Of Person')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='Person.Person')),
            ],
            options={
                'verbose_name_plural': 'Relationships',
            },
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together=set([('person', 'of_person')]),
        ),
    ]
