# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
inhibit_all_warnings!

target 'Assignment' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Assignment
  pod 'Alamofire', '~> 4.4'
  pod 'AlamofireNetworkActivityIndicator', '~> 2.0'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftMessages'

  target 'AssignmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
