# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-23 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relationship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='relation',
            field=models.IntegerField(choices=[(1, 'Father'), (2, 'Mother'), (3, 'Brother'), (4, 'Sister'), (5, 'Husband'), (6, 'Wife'), (7, 'Uncle'), (8, 'Aunt'), (9, 'Son'), (10, 'Daughter'), (11, 'Grand Father'), (12, 'Grand Mother'), (13, 'Boy Friend'), (14, 'Girl Friend')]),
        ),
    ]
